PL/Controllers/ArticleController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Infrastructure;
using BLL.Interfaces;
using Microsoft.AspNet.Identity;
using PagedList;
using PL.Filters;
using PL.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
	/// <summary>
	/// Class that provide all functionality related to Article.
	/// </summary>
	public class ArticleController : Controller
	{
		private readonly IArticleService _service;
		private readonly IMapper _mapper;
		public ArticleController(IArticleService service,IMapper mapper)
		{
			_service = service;
			_mapper = mapper;
		}
		/// <summary>
		/// Give us List of all Articles that in our system.
		/// </summary>
		/// <param name="sort">Tell us how to sort.</param>
		/// <param name="blogId">Tell us to which blog articles related.</param>
		/// <param name="tag">Tell us which tags Articles should have.</param>
		/// <param name="page">For pagination.</param>
		/// <returns>View with articles.</returns>
		public async Task<ActionResult> Index(Sorting? sort, int? blogId,string tag,int?page)		
		{
			ViewBag.Tags = await _service.GetTagsAsync();
			IEnumerable<ArticleDto> list;

			if (sort is null && tag is null && blogId is null)
			{
				list = await _service.GetArticles(Sorting.Date, null, null);
			}
			else
			{
				list = await _service.GetArticles(sort, tag, blogId); 
			}

			ViewBag.Name = tag;
			ViewBag.blog = blogId;
			ViewBag.Sort = sort;
			ViewBag.Page = page ?? 1;
			return View(list.ToPagedList(page??1, 4));			
		}
		/// <summary>
		/// Return articles with specific name with all our filters.
		/// </summary>
		/// <param name="title">Title of Articles.</param>
		/// <param name="page">For pagination</param>
		/// <param name="blogId">Id of current blog.</param>
		/// <param name="tag">Articles related to this tag.</param>
		/// <returns>Articles with same name.</returns>
		[HttpPost]
		public async Task<PartialViewResult> Index(string title,int? page, int? blogId, string tag)
		{
			var list = await _service.GetArticles(Sorting.Date, tag, blogId);
			list = list.Where(s => s.Title.ToLower() == title.ToLower());
			ViewBag.Tags = await _service.GetTagsAsync();
			return PartialView("_ArticlePartial", list.ToPagedList(page ?? 1, 4));
		}
		/// <summary>
		/// Get Article by id.
		/// </summary>
		/// <param name="id">Article's id.</param>
		/// <returns>View with Article.</returns>
		[ActionName("Find")]
		public async Task<ActionResult> GetById(int id)
		{
			var article = await _service.GetArticleByIdAsync(id);
			ViewBag.Tags = await _service.GetTagsAsync();
			ViewBag.Article = article;
			return View(new CommentModel());
		}
		/// <summary>
		/// Method provide info to add new Article.
		/// </summary>
		/// <returns>Article form.</returns>
		[CustomAuthorize]
		public async Task<ActionResult> AddArticle()
		{			
			var tags = await _service.GetTagsAsync();
			ViewBag.Blogs =  new SelectList(await _service.GetBlogsAsync(), "id", "Name");
			var item = new ArticleModel();
			item.TagsName = new Dictionary<string, bool>();
			tags.ToList().ForEach(s => item.TagsName.Add(s.Name, false));
			return View(item);
		}
		/// <summary>
		/// Post method that analyze info that comes from Article form.
		/// </summary>
		/// <param name="model"></param>
		/// <returns></returns>
		[HttpPost]
		[CustomAuthorize]
		public async Task<ActionResult> AddArticle(ArticleModel model)
		{
			List<TagDto> tags = new List<TagDto>();
			foreach(var tag in model.TagsName)
			{
				if (tag.Value)
				{
					tags.Add(new TagDto { Name = tag.Key });
				}
			}
			model.Tags = tags;
			model.TagsName = null;
			model.ProfileId = User.Identity.GetUserId();
			await _service.AddArticleAsync(_mapper.Map<ArticleDto>(model));
			return RedirectToAction("Index");
		}
		/// <summary>
		/// Add comment to article.
		/// </summary>
		/// <param name="model">Comment form.</param>
		/// <returns>Partial view with new list of comments.</returns>
		[HttpPost]
		[ActionName("Find")]
		[CustomAuthorize]
		public async Task<PartialViewResult> AddComment(CommentModel model)		
		{
			
			if (ModelState.IsValid)
			{
				
				var id = HttpContext.GetOwinContext().Authentication.User.Identity.GetUserId();

				model.ProfileId = id;

				await _service.AddCommentToArticleAsync(_mapper.Map<CommentDto>(model));

				var article1 = await _service.GetArticleByIdAsync(model.ArticleId);
				ModelState.Clear();
				return PartialView("_CommentsPartial", article1.Comments);
			}
			var article = await _service.GetArticleByIdAsync(model.ArticleId);
			return PartialView("_CommentsPartial", article.Comments);
		}
		/// <summary>
		/// Add tag to Article.
		/// </summary>
		/// <param name="articleId">Article id.</param>
		/// <param name="tag">Tag name.</param>
		/// <returns>Partial view with tags.</returns>
		[HttpPost]
		[CustomAuthorize]
		public async Task<PartialViewResult> AddTagToArticle(int articleId, string tag)
		{
			var taglist = await _service.GetTagsAsync();

			var article = await _service.GetArticleByIdAsync(articleId);
			TagDto tag1 = null;

			if (tag == "")
			{
				ModelState.AddModelError("", "You can't input empty");
			}
			if (taglist.Any(s => s.Name.ToLower() == tag.ToLower()))
			{
				if (article.Tags.Any(s => s.Name.ToLower() == tag.ToLower()))
				{
					ModelState.AddModelError("", "You have similar tag");
				}
				else
				{
					tag1 = new TagDto { Name = tag, ArticleId = articleId};
				}
			}
			else
			{
				tag1 = new TagDto { Name = tag, ArticleId = articleId };
				_ = taglist.Append(tag1);
			}
			if(article is null)
			{
				ModelState.AddModelError("", "Invalid id");
			}
			
			if (ModelState.IsValid)
			{
				await _service.AddTagToArticleAsync(tag1);
				article?.Tags.Add(tag1);				
			}

			ViewBag.Tags = taglist;

			return PartialView("_IndexPartial", article);
		}
		/// <summary>
		/// Delete tag from article.
		/// </summary>
		/// <param name="articleId">Article id.</param>
		/// <param name="tag">Tag name.</param>
		/// <returns>Partial view with list of tags.</returns>
		[HttpPost]
		[CustomAuthorize]
		public async Task<PartialViewResult> DeleteTagFromArticle(int articleId, string tag)
		{
			var article = await _service.GetArticleByIdAsync(articleId);

			var tag1 = new TagDto{ Name = tag, ArticleId = articleId };			

			article.Tags.Remove(article.Tags.Single(s => s.Name == tag));

			var taglist = await _service.GetTagsAsync();

			await _service.DeleteTagFromArticleAsync(tag1);

			ViewBag.Tags = taglist;

			return PartialView("_IndexPartial", article);
		}
		/// <summary>
		/// Delete specific comment.
		/// </summary>
		/// <param name="commentId">Comment id.</param>
		[HttpPost]
		public async Task DeleteCommment(int commentId)
		{
			await _service.DeleteCommentFromArticleAsync(commentId);
		}
	}
}

PL/Controllers/BlogController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Infrastructure;
using BLL.Interfaces;
using Microsoft.AspNet.Identity;
using PL.Filters;
using PL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PL.Controllers
{
	/// <summary>
	/// Functionality related to Blog.
	/// </summary>
    public class BlogController : Controller
    {
        private readonly IBlogService _service;
		private readonly IMapper _mapper;
		public BlogController(IBlogService service,IMapper mapper )
		{
            _service = service;
			_mapper = mapper; 
		}
		/// <summary>
		/// Show all blogs.
		/// </summary>
		/// <param name="sort">Sort parameter.</param>
		/// <param name="name">Name of blog.</param>
		/// <returns>View with blogs.</returns>
		public async Task<ActionResult> Index(Sorting? sort,string name)
		{
			IEnumerable<BlogDto> list = await _service.GetBlogsAsync(sort);
			if (name != null)
			{
				list = list.Where(s => s.Name.ToLower() == name.ToLower());
				ViewBag.Name = name;
			}
			return View(list);
		}
		/// <summary>
		/// Add blog form.
		/// </summary>
		/// <returns>View with blog form.</returns>
		[CustomAuthorize]
		public ActionResult AddBlog()
		{
			return View();
		}
		/// <summary>
		/// Post method adding blog.
		/// </summary>
		/// <param name="model">Blog from.</param>
		/// <returns>Redirect to Index method.</returns>
		[HttpPost]
		[CustomAuthorize]
		public async Task<ActionResult> AddBlog(BlogModel model)
		{
			if (ModelState.IsValid)
			{
				model.ProfileId = User.Identity.GetUserId();
				await _service.CreateBlog(_mapper.Map<BlogDto>(model));
				return RedirectToAction("Index");
			}
			else
			{
				return View();
			}
			
		}
	}
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title</title>

	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	@RenderSection("css", false)

</head>
<body >

	<div class="container-fluid p-0 m-0">
		<div class="row ">

			<div class="offset-lg-2 col-sm-1 col-lg-1 offset-sm-0 offset-md-0">
				<svg viewBox="0 -20 512 511" xmlns="http://www.w3.org/2000/svg">
					<path d="m67.179688 48.394531h-.101563c-5.523437 0-10 4.476563-10 10 0 5.523438 4.476563 10 10 10h.101563c5.523437 0 10-4.476562 10-10 0-5.523437-4.476563-10-10-10zm0 0" />
					<path d="m116.710938 48.394531h-.101563c-5.523437 0-10 4.476563-10 10 0 5.523438 4.476563 10 10 10h.101563c5.523437 0 10-4.476562 10-10 0-5.523437-4.476563-10-10-10zm0 0" />
					<path d="m166.242188 48.394531h-.101563c-5.523437 0-10 4.476563-10 10 0 5.523438 4.476563 10 10 10h.101563c5.523437 0 10-4.476562 10-10 0-5.523437-4.476563-10-10-10zm0 0" />
					<path d="m444.308594 48.394531h-192.929688c-5.523437 0-10 4.476563-10 10 0 5.519531 4.476563 10 10 10h192.929688c5.523437 0 10-4.480469 10-10 0-5.523437-4.476563-10-10-10zm0 0" />
					<path d="m262.890625 452.4375c-2.628906 0-5.199219 1.070312-7.070313 2.929688-1.859374 1.859374-2.929687 4.441406-2.929687 7.070312s1.070313 5.210938 2.929687 7.070312c1.871094 1.859376 4.441407 2.929688 7.070313 2.929688s5.210937-1.070312 7.070313-2.929688c1.867187-1.859374 2.929687-4.441406 2.929687-7.070312s-1.0625-5.210938-2.929687-7.070312c-1.859376-1.859376-4.441407-2.929688-7.070313-2.929688zm0 0" />
					<path d="m480.230469.5h-448.460938c-17.515625 0-31.769531 14.253906-31.769531 31.769531v408.398438c0 17.519531 14.253906 31.769531 31.769531 31.769531h189.230469c5.523438 0 10-4.476562 10-10s-4.476562-10-10-10h-189.230469c-6.488281 0-11.769531-5.277344-11.769531-11.769531v-324.378907h472v324.378907c0 6.488281-5.28125 11.769531-11.769531 11.769531h-176.5625c-5.523438 0-10 4.476562-10 10s4.476562 10 10 10h176.5625c17.515625 0 31.769531-14.25 31.769531-31.769531v-408.398438c0-17.515625-14.253906-31.769531-31.769531-31.769531zm-460.230469 95.785156v-64.015625c0-6.488281 5.28125-11.769531 11.769531-11.769531h448.460938c6.488281 0 11.769531 5.28125 11.769531 11.769531v64.019531h-472zm0 0" />
					<path d="m178.039062 230.5c0-19.851562-16.148437-36-36-36h-33.667968c-5.523438 0-10 4.476562-10 10v104c0 5.523438 4.476562 10 10 10h33.667968c19.851563 0 36-16.148438 36-36 0-10.214844-4.28125-19.441406-11.140624-26 6.859374-6.558594 11.140624-15.785156 11.140624-26zm-20 52c0 8.820312-7.179687 16-16 16h-23.667968v-32h23.667968c8.820313 0 16 7.175781 16 16zm-39.667968-36v-32h23.667968c8.824219 0 16 7.179688 16 16s-7.175781 16-16 16zm0 0" />
					<path d="m206.648438 194.5c-5.523438 0-10 4.476562-10 10v80.871094c0 18.269531 14.863281 33.128906 33.128906 33.128906 5.523437 0 10-4.476562 10-10s-4.476563-10-10-10c-7.238282 0-13.128906-5.890625-13.128906-13.128906v-80.871094c0-5.523438-4.476563-10-10-10zm0 0" />
					<path d="m324.867188 282.289062c0-19.96875-16.242188-36.214843-36.210938-36.214843s-36.210938 16.246093-36.210938 36.214843 16.246094 36.210938 36.210938 36.210938c19.96875 0 36.210938-16.242188 36.210938-36.210938zm-52.421876 0c0-8.941406 7.273438-16.214843 16.210938-16.214843s16.210938 7.273437 16.210938 16.214843c0 8.9375-7.269532 16.210938-16.210938 16.210938s-16.210938-7.273438-16.210938-16.210938zm0 0" />
					<path d="m377.414062 346.5c-8.9375 0-16.210937-7.273438-16.210937-16.210938 0-5.523437-4.476563-10-10-10s-10 4.476563-10 10c0 19.96875 16.246094 36.210938 36.210937 36.210938 19.96875 0 36.214844-16.242188 36.214844-36.210938v-48c0-19.96875-16.246094-36.214843-36.214844-36.214843-19.964843 0-36.210937 16.246093-36.210937 36.214843s16.246094 36.210938 36.210937 36.210938c5.828126 0 11.332032-1.390625 16.214844-3.847656v15.636718c0 8.9375-7.273437 16.210938-16.214844 16.210938zm0-48c-8.9375 0-16.210937-7.273438-16.210937-16.210938 0-8.941406 7.273437-16.214843 16.210937-16.214843 8.941407 0 16.214844 7.273437 16.214844 16.214843 0 8.9375-7.273437 16.210938-16.214844 16.210938zm0 0" />
					<path d="m108.371094 416.5h295.257812c5.523438 0 10-4.476562 10-10s-4.476562-10-10-10h-295.257812c-5.519532 0-10 4.476562-10 10s4.480468 10 10 10zm0 0" />
				</svg>
			</div>
			<div class="col-lg-5 col-sm-5 col-md-5 text-center blog">
				<h3 class="font-weight-bold" >Personal Blog</h3>
			</div>
			<div class="col-lg-2 col-2 col-sm-2 text-center p-4">
				@if (User.IsInRole("admin") || User.IsInRole("user"))
				{
					<input class="btn btn-danger text-white pb-0 label" type="submit" value=@User.Identity.Name onclick="location.href ='/Account/Info/'">
				}
			</div>
		</div>
	</div>
	<div class="container-fluid justify-content-center mt-2 main">
		<div class="overflow-hidden row justify-content-center">
			<nav class="navbar navbar-light align-content-start bg-white col-1 float-left m-0
				 p-0 align-top border border-dark rounded ">
				<div class="container m-0 p-0 float-left menu">
					<h4 class="navbar-brand" href="#">Menu</h4>

					<ul class="nav flex-column">
						<li class="nav-item " >@Html.ActionLink("Articles", "Index", "Article",null,null)</li>
						<li class="nav-item" >@Html.ActionLink("Blogs", "Index", "Blog", null, null)</li>
						@if (!(User.IsInRole("admin") || User.IsInRole("user")))
						{
							<li class="nav-item">@Html.ActionLink("Login", "Login", "Account", null, null)</li>
							<li class="nav-item">@Html.ActionLink("Register", "Register", "Account", null, null)</li>

						}
						@if (User.IsInRole("admin"))
						{
							<li class="nav-item">@Html.ActionLink("Users", "Index", "Account", null, null)</li>
						}
						@if (User.IsInRole("admin") || User.IsInRole("user"))
						{
							<li class="nav-item">@Html.ActionLink("Logout", "Logout", "Account", null, null)</li>
						}

					</ul>
				</div>
			</nav>
			<div class="overflow-auto col-10 container m-0 p-0 border border-left-0 border-dark bg-white"
				 style="height:60vw;border-width:0.25vw!important">
				@RenderBody()
			</div>
		</div>
	</div>
	<footer class="page-footer font-small" style="background-color: #0000FF">

		<!-- Copyright -->
		<div class="footer-copyright text-center py-3 text-white">
			© 2020 Copyright:
			@Html.ActionLink("Home", "Index", "Article")
			<div>Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
		</div>
		<!-- Copyright -->

	</footer>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/jqueryval")
	@RenderSection("scripts", required: false)
</body>

</html>